### ISSUE TITLE
C++ 20 Module Version

### ISSUE THREAD

**Issue by KeinNiemand** [SpriteOvO/sigmatch#7]
This is already a C++ 20 library so why not have a version of this library that comes as a single C++20 module interface definition file instead of a header, to benefit from faster compile times and other advantages modules have over headers.

Instead of a single header you would have a single .ixx (or whatever extension other compilers use, the extension doesn't matter)

**Comment by SpriteOvO** [comment]
1. At the time the project was developed, C++20 module support was incomplete in most compilers.

2. C++20 modules are compatible with header files, but not vice versa.
